# https://hub.docker.com/r/factoriotools/factorio/

version: "3.5"
services:
  factorio:
    image: factoriotools/factorio
    container_name: factorio
    ports:
      - "${PORT:-34197}:${PORT:-34197}/udp"
      - "27015:27015/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/factorio
    restart: unless-stopped
    stdin_open: true

    environment:
      - PORT=${PORT:-34197}
      # - LOAD_LATEST_SAVE=true
      # - SAVE_NAME=_autosave1
      # - GENERATE_NEW_SAVE=false
